### PR TITLE
First iteration on deployment at IN2P3

### PR DESCRIPTION
**Pull request by airnandez**

### CODE REVIEW

**Comment by timj** [comment]
Thanks. This looks good. I'll rebase it and merge it in.

**Comment by timj** [comment]
Actually, @airnandez I see that you did a fork. Can you please rebase then so that I can merge it? Thanks.

**Comment by timj** [comment]
Ok. I'm experimenting with that new "Update Branch" button to see if I can rebase it myself from GitHub.

**Comment by timj** [comment]
Hmm. Looks like it didn't do what I hoped it would do. It merged my master into the branch on your fork...

**Comment by airnandez** [comment]
Yes, I forked the repo because I didn't realise that I could have commit rights to DM repos. I didn't even think of drawing your attention to that: I'm sorry this has caused trouble.

Anyway, I just rebased branch `u/airnandez/in2p3` of my fork onto `upstream/master`. I don't know if that is enough for you to merge this PR.

Please be aware that my knowledge of git is admittedly limited, so I hope I have not messed things up. If this PR becomes too difficult to merge for you, just le me know and I will start again and submit a separate one with the relevant changes.

**Comment by timj** [comment]
Thanks. I think I've tidied it up. Turns out that GitHub now allow me to push to branches in forks of my own repos (presumably branches that are part of a PR on my repo).

**Comment by airnandez** [comment]
Great !  Thank you !

**Pull request merged**
